#!/usr/bin/env python3
"""
Sudoku Benchmark Analyzer
Usage: python3 analyze.py results_*.csv

Algorithms in CSV:
  Serial               — serial backtracking, row-major cell order
  Serial-MRV           — serial backtracking + MRV heuristic
  BranchBound          — Branch & Bound, row-major, constraint-check bound
  BranchBoundMRV       — Branch & Bound, MRV + forward-checking bound
  OpenMP               — parallel OpenMP tasks, MRV  (threads: 4, 8, 16)
  OMP-BranchBoundMRV   — parallel OpenMP tasks, MRV + forward-checking  (threads: 4, 8, 16)
"""

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import sys
import warnings

warnings.filterwarnings("ignore", category=FutureWarning)

try:
    import seaborn as sns
    HAS_SEABORN = True
except ImportError:
    HAS_SEABORN = False
    print("NOTE: seaborn not installed — efficiency heatmap will be skipped.")
    print("      Install with: pip install seaborn")

# ============================================================
# CONFIG
# ============================================================
PLOT_DIR = "results/plots"
os.makedirs(PLOT_DIR, exist_ok=True)

DIFFICULTIES  = ["Easy", "Medium", "Hard", "Extreme"]
THREAD_COUNTS = [4, 8, 16]

DIFF_COLORS = {
    "Easy":    "#2ca02c",
    "Medium":  "#ff7f0e",
    "Hard":    "#1f77b4",
    "Extreme": "#d62728",
}

# Config labels are generated by config_label(); colours mapped here.
CONFIG_COLORS = {
    "Serial":           "#555555",
    "Serial-MRV":       "#795548",
    "BranchBound":      "#e377c2",
    "BranchBoundMRV":   "#9467bd",
    "OpenMP-4":         "#ff7f0e",
    "OpenMP-8":         "#2ca02c",
    "OpenMP-16":        "#1f77b4",
    "OMP-BBMRV-4":      "#bcbd22",
    "OMP-BBMRV-8":      "#17becf",
    "OMP-BBMRV-16":     "#d62728",
}


# ============================================================
# DATA LOADING & PREPARATION
# ============================================================
def config_label(row):
    alg = row["Algorithm"]
    if alg == "Serial":
        return "Serial"
    elif alg == "Serial-MRV":
        return "Serial-MRV"
    elif alg == "BranchBound":
        return "BranchBound"
    elif alg == "BranchBoundMRV":
        return "BranchBoundMRV"
    elif alg == "OpenMP":
        return f"OpenMP-{int(row['Threads'])}"
    else:  # OMP-BranchBoundMRV
        return f"OMP-BBMRV-{int(row['Threads'])}"


def load_data(paths):
    raw = pd.concat([pd.read_csv(p) for p in paths], ignore_index=True)
    raw = raw[raw["Time_s"] > 0].copy()
    print(f"Loaded {len(raw)} raw timing rows from {len(paths)} file(s).")

    group_keys = ["Board_ID", "Difficulty", "Algorithm", "Threads"]
    time_agg = (
        raw.groupby(group_keys)["Time_s"]
        .agg(Time_s="median", Time_min="min", Time_max="max", Time_std="std")
        .reset_index()
    )
    correct_agg = raw.groupby(group_keys)["Correct"].max().reset_index()

    has_nodes = "Nodes" in raw.columns
    if has_nodes:
        nodes_agg = (
            raw.groupby(group_keys)["Nodes"]
            .agg(Nodes="median", Nodes_min="min", Nodes_max="max")
            .reset_index()
        )

    df = time_agg.merge(correct_agg, on=group_keys)
    if has_nodes:
        df = df.merge(nodes_agg, on=group_keys)
    else:
        df["Nodes"] = pd.NA

    df["Config"] = df.apply(config_label, axis=1)
    df["Cost"]   = df["Threads"] * df["Time_s"]

    print(f"  Aggregated to {len(df)} config rows (median across reps).")
    return df


def compute_speedup(df):
    """
    Two parallel families — each measured against its own serial counterpart:
      OpenMP     — vs Serial-MRV baseline  (parallelism gain; same MRV algorithm, serial vs parallel)
      OMP-BBMRV  — vs BranchBoundMRV baseline (parallelism gain; same MRV+FC algorithm, serial vs parallel)
    """
    results = []

    def _merge(parallel_alg, baseline_alg, family_name):
        baseline = (
            df[df["Algorithm"] == baseline_alg][["Board_ID", "Difficulty", "Time_s"]]
            .rename(columns={"Time_s": "T_serial"})
        )
        parallel = df[df["Algorithm"] == parallel_alg].copy()
        if parallel.empty or baseline.empty:
            return
        merged = parallel.merge(baseline, on=["Board_ID", "Difficulty"])
        merged["Speedup"]    = merged["T_serial"] / merged["Time_s"]
        merged["Efficiency"] = merged["Speedup"] / merged["Threads"]
        merged["Family"]     = family_name
        results.append(merged)

    _merge("OpenMP",             "Serial-MRV",     "OpenMP")
    _merge("OMP-BranchBoundMRV", "BranchBoundMRV", "OMP-BBMRV")

    return pd.concat(results, ignore_index=True) if results else pd.DataFrame()


def compute_bound_effect(df):
    """
    Three pairwise comparisons that isolate the effect of adding the bounding function,
    holding everything else (cell selection strategy, parallelism) constant:

      NoMRV    — Serial        vs BranchBound         (row-major order; plain constraint check added)
      MRV      — Serial-MRV    vs BranchBoundMRV       (MRV order; forward checking added)
      Parallel — OpenMP        vs OMP-BranchBoundMRV   (parallel MRV; forward checking added, same threads)
    """
    results = []

    pairs = [
        ("Serial",     "BranchBound",       "NoMRV",    False),
        ("Serial-MRV", "BranchBoundMRV",    "MRV",      False),
        ("OpenMP",     "OMP-BranchBoundMRV", "Parallel", True),
    ]

    for base_alg, bb_alg, family, match_threads in pairs:
        keys = ["Board_ID", "Difficulty"] + (["Threads"] if match_threads else [])

        base = (
            df[df["Algorithm"] == base_alg][keys + ["Time_s"]]
            .rename(columns={"Time_s": "T_base"})
        )
        bb = (
            df[df["Algorithm"] == bb_alg][keys + ["Time_s"]]
            .rename(columns={"Time_s": "T_bb"})
        )

        if base.empty or bb.empty:
            continue

        merged = base.merge(bb, on=keys)
        merged["Family"] = family
        results.append(merged)

    return pd.concat(results, ignore_index=True) if results else pd.DataFrame()


def _aggregate_speedup(speedup_df, family=None):
    """Aggregate speedup: Σ T_baseline / Σ T_parallel per (Difficulty, Threads)."""
    subset = speedup_df if family is None else speedup_df[speedup_df["Family"] == family]
    rows = []
    for (diff, threads), g in subset.groupby(["Difficulty", "Threads"]):
        agg_speedup = g["T_serial"].sum() / g["Time_s"].sum()
        rows.append({
            "Difficulty":     diff,
            "Threads":        threads,
            "agg_speedup":    agg_speedup,
            "agg_efficiency": agg_speedup / threads,
            "lo":             g["Speedup"].quantile(0.25),
            "hi":             g["Speedup"].quantile(0.75),
        })
    return pd.DataFrame(rows)


# ============================================================
# PLOT 1 — Serial Algorithm Comparison
# ============================================================
def plot_serial_comparison(df):
    print("\n[Plot 1] Serial Algorithm Comparison")

    serial_configs = ["Serial", "Serial-MRV", "BranchBound", "BranchBoundMRV"]
    present = [c for c in serial_configs if c in df["Config"].unique()]
    if not present:
        print("  Skipped — no serial data found.")
        return

    avg = (
        df[df["Config"].isin(present)]
        .groupby(["Difficulty", "Config"])["Time_s"]
        .mean()
        .reset_index()
    )

    x     = np.arange(len(DIFFICULTIES))
    n     = len(present)
    width = 0.8 / n

    fig, ax = plt.subplots(figsize=(11, 5))

    for i, cfg in enumerate(present):
        vals = (
            avg[avg["Config"] == cfg]
            .set_index("Difficulty")
            .reindex(DIFFICULTIES)["Time_s"]
            .values
        )
        offset = (i - n / 2 + 0.5) * width
        ax.bar(x + offset, vals, width * 0.9,
               label=cfg, color=CONFIG_COLORS.get(cfg, "#888888"))

    ax.set_xlabel("Difficulty")
    ax.set_ylabel("Average Solve Time (seconds, log scale)")
    ax.set_title("Serial Algorithm Comparison\n"
                 "Serial  |  Serial-MRV  |  Branch & Bound  |  Branch & Bound MRV")
    ax.set_xticks(x)
    ax.set_xticklabels(DIFFICULTIES)
    ax.set_yscale("log")
    ax.legend()
    ax.grid(True, alpha=0.3, axis="y")

    fig.tight_layout()
    path = os.path.join(PLOT_DIR, "serial_comparison.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


# ============================================================
# PLOT 2 — Speedup vs Threads (one subplot per parallel family)
# ============================================================
def plot_speedup_vs_threads(speedup_df):
    print("\n[Plot 2] Speedup vs Threads")

    if speedup_df.empty:
        print("  Skipped — no speedup data.")
        return

    families = [f for f in ["OpenMP", "OMP-BBMRV"] if f in speedup_df["Family"].values]
    if not families:
        print("  Skipped — no matching families.")
        return

    subtitles = {
        "OpenMP":    "OpenMP  (vs Serial-MRV baseline — parallelism gain only)",
        "OMP-BBMRV": "OMP Branch & Bound MRV  (vs BranchBoundMRV baseline — parallelism gain only)",
    }

    fig, axes = plt.subplots(1, len(families), figsize=(7 * len(families), 5), sharey=False)
    if len(families) == 1:
        axes = [axes]

    for ax, family in zip(axes, families):
        agg = _aggregate_speedup(speedup_df, family=family)
        ax.plot(THREAD_COUNTS, THREAD_COUNTS, "k--", lw=1, label="Ideal (linear)", zorder=1)

        for diff in DIFFICULTIES:
            s = agg[agg["Difficulty"] == diff].sort_values("Threads")
            if s.empty:
                continue
            ax.plot(s["Threads"], s["agg_speedup"], marker="o",
                    color=DIFF_COLORS[diff], label=diff, zorder=2)
            ax.fill_between(s["Threads"], s["lo"], s["hi"],
                            color=DIFF_COLORS[diff], alpha=0.12)

        ax.set_xlabel("Threads")
        ax.set_ylabel("Speedup  S = Σ T_baseline / Σ T_parallel")
        ax.set_title(subtitles[family])
        ax.set_xticks(THREAD_COUNTS)
        ax.legend()
        ax.grid(True, alpha=0.3)
        ax.set_xlim(left=0)
        ax.set_ylim(bottom=0)

    fig.suptitle("Speedup vs Thread Count by Difficulty\n"
                 "(line = aggregate speedup; band = Q1–Q3 per-puzzle)", fontsize=13)
    fig.tight_layout()
    path = os.path.join(PLOT_DIR, "speedup_vs_threads.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


# ============================================================
# PLOT 3 — Runtime vs Threads (one subplot per parallel family)
# ============================================================
def plot_runtime_vs_threads(df):
    print("\n[Plot 3] Runtime vs Threads")

    families = {
        "OpenMP":    ("Serial-MRV",     "OpenMP"),
        "OMP-BBMRV": ("BranchBoundMRV", "OMP-BranchBoundMRV"),
    }
    subtitles = {
        "OpenMP":    "OpenMP  (Serial-MRV baseline at x=1)",
        "OMP-BBMRV": "OMP Branch & Bound MRV  (BranchBoundMRV baseline at x=1)",
    }

    fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=False)

    for ax, (family, (s_alg, p_alg)) in zip(axes, families.items()):
        for diff in DIFFICULTIES:
            x_vals, y_vals = [], []

            s = df[(df["Algorithm"] == s_alg) & (df["Difficulty"] == diff)]
            if not s.empty:
                x_vals.append(1)
                y_vals.append(s["Time_s"].mean())

            for t in THREAD_COUNTS:
                p = df[
                    (df["Algorithm"] == p_alg) &
                    (df["Difficulty"] == diff) &
                    (df["Threads"] == t)
                ]
                if not p.empty:
                    x_vals.append(t)
                    y_vals.append(p["Time_s"].mean())

            if x_vals:
                ax.plot(x_vals, y_vals, marker="o",
                        color=DIFF_COLORS[diff], label=diff)

        ax.set_xlabel("Threads  (1 = serial baseline)")
        ax.set_ylabel("Average Solve Time (seconds)")
        ax.set_title(subtitles[family])
        ax.set_xticks([1] + THREAD_COUNTS)
        ax.set_yscale("log")
        ax.legend()
        ax.grid(True, alpha=0.3, which="both")

    fig.suptitle("Runtime vs Thread Count by Difficulty", fontsize=13)
    fig.tight_layout()
    path = os.path.join(PLOT_DIR, "runtime_vs_threads.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


# ============================================================
# PLOT 4 — Runtime Distribution — Violin Plots
# ============================================================
def plot_runtime_distribution(df):
    print("\n[Plot 4] Runtime Distribution Violin Plots")

    all_configs = (
        ["Serial", "Serial-MRV", "BranchBound", "BranchBoundMRV"]
        + [f"OpenMP-{t}"    for t in THREAD_COUNTS]
        + [f"OMP-BBMRV-{t}" for t in THREAD_COUNTS]
    )
    configs = [c for c in all_configs if c in df["Config"].unique()]

    fig, axes = plt.subplots(1, len(DIFFICULTIES), figsize=(22, 5), sharey=False)
    fig.suptitle("Solve Time Distribution by Difficulty and Configuration", fontsize=13)

    for ax, diff in zip(axes, DIFFICULTIES):
        subset = df[df["Difficulty"] == diff]

        log_data = [
            np.log10(subset[subset["Config"] == cfg]["Time_s"].dropna().values)
            for cfg in configs
        ]
        valid = [(d, c) for d, c in zip(log_data, configs) if len(d) > 1]
        if not valid:
            ax.set_title(diff)
            continue
        valid_data, valid_configs = zip(*valid)

        parts = ax.violinplot(valid_data, positions=range(len(valid_configs)),
                              showmedians=True, showextrema=True)

        for body, cfg in zip(parts["bodies"], valid_configs):
            body.set_facecolor(CONFIG_COLORS.get(cfg, "#888888"))
            body.set_alpha(0.72)
            body.set_edgecolor("black")
            body.set_linewidth(0.5)

        for key in ("cbars", "cmins", "cmaxes"):
            if key in parts:
                parts[key].set_color("black")
                parts[key].set_linewidth(0.8)
        if "cmedians" in parts:
            parts["cmedians"].set_color("white")
            parts["cmedians"].set_linewidth(2.0)

        ax.set_xticks(range(len(valid_configs)))
        ax.set_xticklabels(valid_configs, rotation=40, ha="right", fontsize=7)
        ax.set_title(diff, fontsize=11)
        ax.set_ylabel("log₁₀(Time / s)" if diff == DIFFICULTIES[0] else "")

        lo, hi = ax.get_ylim()
        tick_pows = [p for p in range(-6, 2) if lo - 0.15 <= p <= hi + 0.15]
        if tick_pows:
            ax.set_yticks(tick_pows)
            ax.set_yticklabels([f"$10^{{{p}}}$" for p in tick_pows])

        ax.grid(True, alpha=0.3, axis="y")

    fig.tight_layout()
    path = os.path.join(PLOT_DIR, "runtime_distribution.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


# ============================================================
# PLOT 5 — Parallel Efficiency Heatmap (one per family)
# ============================================================
def plot_efficiency_heatmap(speedup_df):
    if not HAS_SEABORN:
        print("\n[Plot 5] Efficiency heatmap — SKIPPED (seaborn not installed)")
        return

    print("\n[Plot 5] Parallel Efficiency Heatmap")

    if speedup_df.empty:
        print("  Skipped — no speedup data.")
        return

    families = [f for f in ["OpenMP", "OMP-BBMRV"] if f in speedup_df["Family"].values]
    subtitles = {
        "OpenMP":    "OpenMP  (vs Serial)",
        "OMP-BBMRV": "OMP Branch & Bound MRV  (vs BranchBoundMRV)",
    }

    fig, axes = plt.subplots(1, len(families), figsize=(6 * len(families), 4))
    if len(families) == 1:
        axes = [axes]

    for ax, family in zip(axes, families):
        agg   = _aggregate_speedup(speedup_df, family=family)
        pivot = (
            agg.pivot(index="Difficulty", columns="Threads", values="agg_efficiency")
            .reindex(DIFFICULTIES)
        )
        sns.heatmap(pivot, annot=True, fmt=".2f", cmap="YlGn",
                    vmin=0, vmax=1.0, ax=ax, linewidths=0.5,
                    cbar_kws={"label": "Aggregate Efficiency  E = S / P"})
        ax.set_title(subtitles[family])
        ax.set_xlabel("Threads")
        ax.set_ylabel("Difficulty")

    fig.suptitle("Parallel Efficiency by Difficulty and Thread Count  (ideal = 1.0)", fontsize=13)
    fig.tight_layout()
    path = os.path.join(PLOT_DIR, "efficiency_heatmap.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


# ============================================================
# PLOT 6 — All Configurations Absolute Runtime (grouped bar)
# ============================================================
def plot_all_configs(df):
    print("\n[Plot 6] All Configurations Absolute Runtime")

    all_configs = (
        ["Serial", "Serial-MRV", "BranchBound", "BranchBoundMRV"]
        + [f"OpenMP-{t}"    for t in THREAD_COUNTS]
        + [f"OMP-BBMRV-{t}" for t in THREAD_COUNTS]
    )
    configs = [c for c in all_configs if c in df["Config"].unique()]

    avg = df.groupby(["Difficulty", "Config"])["Time_s"].mean().reset_index()

    x     = np.arange(len(DIFFICULTIES))
    n     = len(configs)
    width = 0.85 / n

    fig, ax = plt.subplots(figsize=(14, 5))

    for i, cfg in enumerate(configs):
        vals = (
            avg[avg["Config"] == cfg]
            .set_index("Difficulty")
            .reindex(DIFFICULTIES)["Time_s"]
            .values
        )
        offset = (i - n / 2 + 0.5) * width
        ax.bar(x + offset, vals, width * 0.92,
               label=cfg, color=CONFIG_COLORS.get(cfg, "#888888"))

    ax.set_xlabel("Difficulty")
    ax.set_ylabel("Average Solve Time (seconds, log scale)")
    ax.set_title("Average Solve Time: All Algorithm Configurations")
    ax.set_xticks(x)
    ax.set_xticklabels(DIFFICULTIES)
    ax.set_yscale("log")
    ax.legend(ncol=2, fontsize=8)
    ax.grid(True, alpha=0.3, axis="y")

    fig.tight_layout()
    path = os.path.join(PLOT_DIR, "all_configs_runtime.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


# ============================================================
# PLOT 7 — Cost vs Threads (one subplot per parallel family)
# ============================================================
def plot_cost_vs_threads(df):
    print("\n[Plot 7] Cost vs Threads")

    families = {
        "OpenMP":    ("Serial-MRV",     "OpenMP"),
        "OMP-BBMRV": ("BranchBoundMRV", "OMP-BranchBoundMRV"),
    }
    subtitles = {
        "OpenMP":    "OpenMP  (Serial-MRV baseline at x=1)",
        "OMP-BBMRV": "OMP Branch & Bound MRV  (BranchBoundMRV baseline at x=1)",
    }

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    for ax, (family, (s_alg, p_alg)) in zip(axes, families.items()):
        for diff in DIFFICULTIES:
            x_vals, y_vals = [], []

            s = df[(df["Algorithm"] == s_alg) & (df["Difficulty"] == diff)]
            if not s.empty:
                serial_cost = 1 * s["Time_s"].mean()
                x_vals.append(1)
                y_vals.append(serial_cost)
                ax.axhline(serial_cost, color=DIFF_COLORS[diff],
                           lw=1, linestyle="--", alpha=0.4)

            for t in THREAD_COUNTS:
                p = df[
                    (df["Algorithm"] == p_alg) &
                    (df["Difficulty"] == diff) &
                    (df["Threads"] == t)
                ]
                if not p.empty:
                    x_vals.append(t)
                    y_vals.append(t * p["Time_s"].mean())

            if x_vals:
                ax.plot(x_vals, y_vals, marker="s",
                        color=DIFF_COLORS[diff], label=diff, zorder=2)

        ax.set_xlabel("Threads  (1 = serial baseline)")
        ax.set_ylabel("Cost  C(P) = P × T(P)  (thread-seconds)")
        ax.set_title(subtitles[family])
        ax.set_xticks([1] + THREAD_COUNTS)
        ax.set_yscale("log")
        ax.grid(True, alpha=0.3, which="both")

        dash_proxy = mpatches.Patch(facecolor="none", edgecolor="gray",
                                    linestyle="--", label="serial C(1) reference")
        handles, labels = ax.get_legend_handles_labels()
        ax.legend(handles=handles + [dash_proxy],
                  labels=labels + ["serial C(1) reference"], fontsize=8)

    fig.suptitle("Parallel Cost vs Thread Count\n"
                 "Flat line ≈ cost-optimal  |  Rising line → growing overhead", fontsize=13)
    fig.tight_layout()
    path = os.path.join(PLOT_DIR, "cost_vs_threads.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


# ============================================================
# PLOT 8 — Node Exploration Comparison
# ============================================================
def plot_node_exploration(df):
    print("\n[Plot 8] Node Exploration Comparison")

    if "Nodes" not in df.columns or df["Nodes"].isna().all():
        print("  Skipped — no Nodes data found.")
        return

    all_configs = (
        ["Serial", "Serial-MRV", "BranchBound", "BranchBoundMRV"]
        + [f"OpenMP-{t}"    for t in THREAD_COUNTS]
        + [f"OMP-BBMRV-{t}" for t in THREAD_COUNTS]
    )
    configs = [c for c in all_configs if c in df["Config"].unique()]

    avg = df.groupby(["Difficulty", "Config"])["Nodes"].median().reset_index()

    x     = np.arange(len(DIFFICULTIES))
    n     = len(configs)
    width = 0.85 / n

    fig, ax = plt.subplots(figsize=(14, 5))

    for i, cfg in enumerate(configs):
        vals = (
            avg[avg["Config"] == cfg]
            .set_index("Difficulty")
            .reindex(DIFFICULTIES)["Nodes"]
            .values
        )
        offset = (i - n / 2 + 0.5) * width
        ax.bar(x + offset, vals, width * 0.92,
               label=cfg, color=CONFIG_COLORS.get(cfg, "#888888"))

    ax.set_xlabel("Difficulty")
    ax.set_ylabel("Median Nodes Explored (log scale)")
    ax.set_title("Search Space Explored: Nodes per Algorithm Configuration\n"
                 "(one node = one value placement attempted)")
    ax.set_xticks(x)
    ax.set_xticklabels(DIFFICULTIES)
    ax.set_yscale("log")
    ax.legend(ncol=2, fontsize=8)
    ax.grid(True, alpha=0.3, axis="y")

    fig.tight_layout()
    path = os.path.join(PLOT_DIR, "node_exploration.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


# ============================================================
# PLOT 9 — Bound Effect: pairwise comparison within each tier
# ============================================================
def plot_bound_effect(bound_df):
    print("\n[Plot 9] Bound Effect Comparison")

    if bound_df.empty:
        print("  Skipped — no data.")
        return

    panels = [
        ("NoMRV",    "Serial  vs  BranchBound",
         "Row-major cell order\nPlain constraint check added as bound"),
        ("MRV",      "Serial-MRV  vs  BranchBoundMRV",
         "MRV cell order\nForward checking added as bound"),
        ("Parallel", "OpenMP  vs  OMP-BranchBoundMRV",
         "Parallel MRV\nForward checking added as bound  (matched thread count)"),
    ]
    panels = [(f, t, s) for f, t, s in panels if f in bound_df["Family"].values]
    if not panels:
        print("  Skipped — no matching families.")
        return

    fig, axes = plt.subplots(1, len(panels), figsize=(7 * len(panels), 5), sharey=False)
    if len(panels) == 1:
        axes = [axes]

    for ax, (family, title, subtitle) in zip(axes, panels):
        subset = bound_df[bound_df["Family"] == family]
        ax.axhline(1.0, color="black", lw=1.2, linestyle="--", label="Break-even  (ratio = 1)")

        if family == "Parallel":
            for t in THREAD_COUNTS:
                s = subset[subset["Threads"] == t]
                if s.empty:
                    continue
                agg = (
                    s.groupby("Difficulty")[["T_base", "T_bb"]]
                    .sum()
                    .reindex(DIFFICULTIES)
                )
                ratio = (agg["T_base"] / agg["T_bb"]).values
                ax.plot(DIFFICULTIES, ratio, marker="o", label=f"{t} threads")
        else:
            agg = (
                subset.groupby("Difficulty")[["T_base", "T_bb"]]
                .sum()
                .reindex(DIFFICULTIES)
            )
            ratio = (agg["T_base"] / agg["T_bb"]).values
            color = CONFIG_COLORS.get("BranchBound" if family == "NoMRV" else "BranchBoundMRV", "#888888")
            ax.plot(DIFFICULTIES, ratio, marker="o", color=color, linewidth=2, markersize=8,
                    label="B&B ratio")

        ax.set_title(f"{title}\n{subtitle}", fontsize=10)
        ax.set_xlabel("Difficulty")
        ax.set_ylabel("T_without_bound / T_with_bound\n(> 1  B&B faster  |  < 1  B&B slower)")
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)

    fig.suptitle("Bounding Function Overhead / Benefit by Difficulty\n"
                 "Each panel holds cell-selection strategy and parallelism constant",
                 fontsize=13)
    fig.tight_layout()
    path = os.path.join(PLOT_DIR, "bound_effect.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {path}")


# ============================================================
# SUMMARY TABLE
# ============================================================
def save_summary_table(df, speedup_df):
    print("\n[Table] Summary")

    time_agg = (
        df.groupby(["Difficulty", "Config"])["Time_s"]
        .agg(Time_median="median", Time_mean="mean", Time_std="std",
             Time_min="min", Time_max="max")
        .reset_index()
    )
    cost_agg = (
        df.groupby(["Difficulty", "Config"])["Cost"]
        .mean().reset_index()
        .rename(columns={"Cost": "Cost_mean"})
    )
    has_nodes = "Nodes" in df.columns and not df["Nodes"].isna().all()
    nodes_agg = (
        df.groupby(["Difficulty", "Config"])["Nodes"]
        .agg(Nodes_median="median", Nodes_mean="mean")
        .reset_index()
    ) if has_nodes else None

    agg_rows = []
    if not speedup_df.empty:
        for (diff, config), g in speedup_df.groupby(["Difficulty", "Config"]):
            threads     = g["Threads"].iloc[0]
            agg_speedup = g["T_serial"].sum() / g["Time_s"].sum()
            agg_rows.append({
                "Difficulty":     diff,
                "Config":         config,
                "Agg_Speedup":    agg_speedup,
                "Agg_Efficiency": agg_speedup / threads,
            })
    agg_metrics = (pd.DataFrame(agg_rows) if agg_rows
                   else pd.DataFrame(columns=["Difficulty", "Config", "Agg_Speedup", "Agg_Efficiency"]))

    mean_speedup = (
        speedup_df.groupby(["Difficulty", "Config"])["Speedup"]
        .mean().reset_index()
        .rename(columns={"Speedup": "Speedup_mean"})
    ) if not speedup_df.empty else pd.DataFrame(columns=["Difficulty", "Config", "Speedup_mean"])

    mean_efficiency = (
        speedup_df.groupby(["Difficulty", "Config"])["Efficiency"]
        .mean().reset_index()
        .rename(columns={"Efficiency": "Efficiency_mean"})
    ) if not speedup_df.empty else pd.DataFrame(columns=["Difficulty", "Config", "Efficiency_mean"])

    # Speedup = 1.0 reference rows for each serial baseline used in compute_speedup
    for s_config in ["Serial-MRV", "BranchBoundMRV"]:
        if s_config not in time_agg["Config"].values:
            continue
        ref = time_agg[time_agg["Config"] == s_config][["Difficulty", "Config"]].copy()
        ref["Agg_Speedup"]    = 1.0
        ref["Agg_Efficiency"] = 1.0
        agg_metrics = pd.concat([agg_metrics, ref], ignore_index=True)

        ref2 = ref[["Difficulty", "Config"]].copy()
        ref2["Speedup_mean"] = 1.0
        mean_speedup = pd.concat([mean_speedup, ref2], ignore_index=True)

        ref3 = ref[["Difficulty", "Config"]].copy()
        ref3["Efficiency_mean"] = 1.0
        mean_efficiency = pd.concat([mean_efficiency, ref3], ignore_index=True)

    summary = (
        time_agg
        .merge(cost_agg,        on=["Difficulty", "Config"], how="left")
        .merge(agg_metrics,     on=["Difficulty", "Config"], how="left")
        .merge(mean_speedup,    on=["Difficulty", "Config"], how="left")
        .merge(mean_efficiency, on=["Difficulty", "Config"], how="left")
    )
    if nodes_agg is not None:
        summary = summary.merge(nodes_agg, on=["Difficulty", "Config"], how="left")

    config_order = (
        ["Serial", "Serial-MRV", "BranchBound", "BranchBoundMRV"]
        + [f"OpenMP-{t}"    for t in THREAD_COUNTS]
        + [f"OMP-BBMRV-{t}" for t in THREAD_COUNTS]
    )
    summary["Config"]     = pd.Categorical(summary["Config"],     categories=config_order, ordered=True)
    summary["Difficulty"] = pd.Categorical(summary["Difficulty"], categories=DIFFICULTIES,  ordered=True)
    summary = summary.sort_values(["Difficulty", "Config"])

    path = os.path.join(PLOT_DIR, "summary_table.csv")
    summary.to_csv(path, index=False, float_format="%.6f")
    print(f"  Saved: {path}")

    pd.set_option("display.max_rows",     200)
    pd.set_option("display.float_format", "{:.4f}".format)
    pd.set_option("display.width",        220)
    print(summary.to_string(index=False))


# ============================================================
# MAIN
# ============================================================
if __name__ == "__main__":
    import glob as _glob

    if len(sys.argv) < 2:
        print("Usage: python3 analyze.py results_*.csv")
        sys.exit(1)

    paths = []
    for arg in sys.argv[1:]:
        expanded = _glob.glob(arg)
        paths.extend(expanded if expanded else [arg])

    if not paths:
        print("No matching files found.")
        sys.exit(1)

    df = load_data(paths)
    df_correct = df[df["Correct"] == 1].copy()
    print(f"  {len(df_correct)} rows with Correct=1 used for timing plots.")

    speedup_df = compute_speedup(df_correct)
    if not speedup_df.empty:
        speedup_df["Config"] = speedup_df.apply(config_label, axis=1)

    bound_df = compute_bound_effect(df_correct)

    plot_serial_comparison(df_correct)
    plot_speedup_vs_threads(speedup_df)
    plot_runtime_vs_threads(df_correct)
    plot_runtime_distribution(df_correct)
    plot_efficiency_heatmap(speedup_df)
    plot_all_configs(df_correct)
    plot_cost_vs_threads(df_correct)
    plot_node_exploration(df_correct)
    plot_bound_effect(bound_df)
    save_summary_table(df_correct, speedup_df)

    print(f"\nAll plots written to: {PLOT_DIR}/")
